### ISSUE TITLE
Code generation bugs on OS X with GCC

### ISSUE THREAD

**Issue by lkuper** [IntelLabs/ParallelAccelerator.jl#1]
On OS X, for several of our examples, we are generating code that GCC fails to compile.  For instance, see [gaussian-blur](https://travis-ci.org/IntelLabs/ParallelAccelerator.jl/jobs/86522125#L2706), [opt-flow](https://travis-ci.org/IntelLabs/ParallelAccelerator.jl/jobs/86522125#L2770), and [quant](https://travis-ci.org/IntelLabs/ParallelAccelerator.jl/jobs/86522125#L2889).

However, this might just be a matter of needing to pass the `-std=c++11 -stdlib=libc++` flags.

**Comment by malmaud** [comment]
Seems likely that hypothesis is correct since the same tests that are failing on OSX are giving this warning on Linux with GCC:

```
/root/.julia/v0.4/ParallelAccelerator/src/../deps/generated/cgen_output5.cpp:2370:9: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
 GenSym4 = {GenSym2, GenSym3};
```

**Comment by ehsantn** [comment]
In some places we were trying to avoid depending on C++11, but seems like we are assuming C++11 in code generation anyways. I don't think too many compiler lack it these days so I'll just add it.
