### ISSUE TITLE
Pkg.test("ParallelAccelerator") failed on ubuntu

### ISSUE THREAD

**Issue by imanpanahi** [IntelLabs/ParallelAccelerator.jl#101]
I have installed "ParallelAccelerator" according to this "http://parallelacceleratorjl.readthedocs.io/en/latest/install.html" guide.
When i run Pkg.test("ParallelAccelerator") it gives me following error:

julia> Pkg.test("ParallelAccelerator")
INFO: Computing test dependencies for ParallelAccelerator...
INFO: Installing Cairo v0.2.31
INFO: Installing ColorVectorSpace v0.1.4
INFO: Installing DocOpt v0.1.2
INFO: Installing FileIO v0.0.6
INFO: Installing Graphics v0.1.3
INFO: Installing ImageMagick v0.1.6
INFO: Installing Images v0.5.5
INFO: Installing IniFile v0.2.5
INFO: Installing SIUnits v0.0.6
INFO: Installing TexExtensions v0.0.3
INFO: Installing Tk v0.3.8
INFO: Installing Winston v0.11.13
INFO: Installing Zlib v0.1.12
INFO: Building Cairo
INFO: Building ImageMagick
INFO: Building Tk
INFO: Testing ParallelAccelerator
ERROR: LoadError: LoadError: LoadError: UndefVarError: is_apple not defined
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in require at ./loading.jl:259
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/iman/.julia/v0.4/ParallelAccelerator/src/cgen.jl, in expression starting on line 146
while loading /home/iman/.julia/v0.4/ParallelAccelerator/src/ParallelAccelerator.jl, in expression starting on line 253
while loading /home/iman/.julia/v0.4/ParallelAccelerator/test/runtests.jl, in expression starting on line 26
=========================[ ERROR: ParallelAccelerator ]=========================

failed process: Process(`/home/iman/julia/bin/julia --check-bounds=yes --code-coverage=none --color=yes /home/iman/.julia/v0.4/ParallelAccelerator/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: Removing Cairo v0.2.31
INFO: Removing ColorVectorSpace v0.1.4
INFO: Removing DocOpt v0.1.2
INFO: Removing FileIO v0.0.6
INFO: Removing Graphics v0.1.3
INFO: Removing ImageMagick v0.1.6
INFO: Removing Images v0.5.5
INFO: Removing IniFile v0.2.5
INFO: Removing SIUnits v0.0.6
INFO: Removing TexExtensions v0.0.3
INFO: Removing Tk v0.3.8
INFO: Removing Winston v0.11.13
INFO: Removing Zlib v0.1.12
ERROR: ParallelAccelerator had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
  in test at pkg.jl:71

-------------------
when i run "using ParallelAccelerator" i get  this error:

LoadError: LoadError: LoadError: UndefVarError: is_apple not defined
while loading /home/iman/.julia/v0.4/ParallelAccelerator/src/cgen.jl, in expression starting on line 146
while loading /home/iman/.julia/v0.4/ParallelAccelerator/src/ParallelAccelerator.jl, in expression starting on line 253
while loading In[7], in expression starting on line 1

-------------------------

I'm running julia v4.5 in ubuntu 16.04

thank you

**Comment by DrTodd13** [comment]
Can you try updating the Compat package and then trying again Pkg.test for ParallelAccelerator again?

**Comment by imanpanahi** [comment]
thank you, its solved the problem
