### ISSUE TITLE
General handling of ranges and BitArrays

### ISSUE THREAD

**Issue by ehsantn** [IntelLabs/ParallelAccelerator.jl#13]
Ranges and BitArrays should be handled in a more general way. Using different kinds of ranges and BitArrays in multiple dimensions for array access should work. 

`parfors` with ranges should be fused whenever possible.

**Comment by ehsantn** [comment]
We need symbolic math for making sense of ranges. 

Example: Black-Scholes with initialization comprehensions inside `@acc` function has `iterations+1-1` in its range.

**Comment by DrTodd13** [comment]
There will probably always be parfors that we could fuse with additional analysis.  Even additional analysis means you can fuse more.  What I've done so far is basically expression comparison after simplification.  It isn't full-blown symbolic math but seems to be good enough for the simple sorts of ranges we've seen so far.  Again, it would probably be easy to do something slightly more complicated that wouldn't simplify and wouldn't fuse but I'm not liking our options for full-blown symbolic math.  I don't want to pull in sympy and implementing full symbolic math seems like overkill.

I'm going to call this closed in the range-fusion branch.  After merge, we can open a new issue if there is something else that needs to be done there.
