### ISSUE TITLE
AstWalkCallback for DomainLambda

### ISSUE THREAD

**Issue by ehsantn** [IntelLabs/ParallelAccelerator.jl#133]
`AstWalkCallback` in DomainIR doesn't recurse inside the body. Therefore, AST walks like copy propagation don't go inside.

**Comment by ninegua** [comment]
So is this about renaming an escaping variable? Can you give me an example of where you need to do this?

**Comment by ehsantn** [comment]
No, it's not renaming. For example, copy propagation handles DomainLambda in [here](https://github.com/IntelLabs/ParallelAccelerator.jl/blob/master/src/parallel-ir-simplify.jl#L701) and returns `ASTWALK_RECURSE`. But DomainIR doesn't go inside body [here](https://github.com/IntelLabs/ParallelAccelerator.jl/blob/master/src/domain-ir.jl#L2877) and just returns. A good example is the kernel density code where some obvious constants are not replaced.

**Comment by ninegua** [comment]
I don't think AstWalker ever goes into nested expressions. We made a special case for `replaceExprWithDict!` to explicitly deal with escaping variables. If this is the function you use in copy propagation, I can make it accommodate `DomainLambda` too.

**Comment by ninegua** [comment]
Wait, I believe `replaceExprWithDict!` is already setup to handle `DomainLambda` just fine. The relevant code is [here](https://github.com/IntelLabs/ParallelAccelerator.jl/blob/master/src/domain-ir.jl#L271-L275). So copy propagation has to use `replaceExprWithDict!` if it is not doing so.

**Comment by ehsantn** [comment]
`replaceExprWithDict` is a special case. Is traversing DomainLambda's body fundamentally wrong?

**Comment by ninegua** [comment]
I wouldn't say all nested traversals are wrong, but variable name clashing is a delicate matter and must be handled with care, which is often times specific to use scenario, so it is best not to generalize the logic into generic traversal code, as most traversals are not interested in nested case, and would be wrong otherwise if not handled carefully.

**Comment by ehsantn** [comment]
Ok, makes sense. I will use special code then.
