### ISSUE TITLE
Control degree of parallelism?

### ISSUE THREAD

**Issue by pancetta** [IntelLabs/ParallelAccelerator.jl#141]
Is there a way to actually control the degree of parallelism? In particular, how do I control and/or change the number of processes used for e.g. `runStencil`?

**Comment by ehsantn** [comment]
ParallelAccelerator uses OpenMP as the parallel backend. You can change the number of threads using `OMP_NUM_THREADS ` environment variable. Changing it for a specific region of the function is not provided.

**Comment by pancetta** [comment]
Thanks for your answer! Are there any plans to include distributed memory parallelism?

**Comment by ehsantn** [comment]
Not for ParallelAccelerator. [HPAT](https://github.com/IntelLabs/HPAT.jl) provides distributed-memory parallelism for data analytics workloads.

**Comment by lkuper** [comment]
I'm going through and cleaning up some old open issues.  It looks like this was sufficiently answered, but if not, feel free to re-open.  Thanks!
