### ISSUE TITLE
Add Tony Kelman

### ISSUE THREAD

**Issue by ViralBShah** [IntelLabs/ParallelAccelerator.jl#2]
Could you also add @tkelman to these repos? He just recently joined Julia Computing, and would be a valuable person to include here, especially when it comes close to release.

BTW, this is looking fantastic. Looking forward to trying it out soon.

**Comment by lkuper** [comment]
The repos are public anyway, but I've added @tkelman to our organization.

**Comment by ViralBShah** [comment]
Didn't realize that. Thanks.
