### ISSUE TITLE
Write a tutorial

### ISSUE THREAD

**Issue by lkuper** [IntelLabs/ParallelAccelerator.jl#27]
We need a tutorial that explains the ParallelAccelerator workflow and walks through how to accelerate an example program.

**Comment by olegmikul** [comment]
Yes, indeed.

I would like also to have acceleration ratio for each example, so it would be good to have 2 codes/variants for each example - with and without an accelerator. May be tweak by arguments to make it easy. It is hard to get filling on advantages of the accelerator without such comparison. For example, in samples for intel compilers we have an easy way to get speed up ratio for using various pragmas on your system.

**Comment by ninegua** [comment]
You can run the same example programs with `PROSPECT_MODE=none` set in the environment. This gives performance without using ParallelAccelerator. But I agree, a performance comparison diagram is much needed in the README.

**Comment by lkuper** [comment]
+1 for a performance comparison in the README.

**Comment by olegmikul** [comment]
Ok, thanks for suggestions, it works. Now I have a tough question - how to speed up the overall walking time (SELFPRIMED+SELTIMED) to get it faster than running without ParallelAccelerator? Similar to, say, using Gadfly - first time or for new data it takes long time to compile. Is there any way for Julia to resolve that issue?

**Comment by lkuper** [comment]
@olegmikul Yep -- that delay the first time is the time it takes ParallelAccelerator to compile.  The best solution at the moment is to embed the ParallelAccelerator package into your Julia executable using `ParallelAccelerator.embed()`, as described [here](https://github.com/IntelLabs/ParallelAccelerator.jl#faster-compilation-via-userimgjl).  This only works if you've installed Julia from source, though.

**Comment by olegmikul** [comment]
@lkuper Thank you, it works. With some warning, but works.

**Comment by lkuper** [comment]
Assigning this to myself to work on in January.

**Comment by lkuper** [comment]
I think the [blog post published last week](http://julialang.org/blog/2016/03/parallelaccelerator) captures pretty well what I was hoping to achieve with a tutorial.  It covers example usage and has a performance comparison.  I'll link to it from our README.

With that, I'm going to close this issue, but let me know if there's something missing from the blog post that you think ought to be covered in our docs.
