### ISSUE TITLE
CGen error for test_at_mul_b.jl

### ISSUE THREAD

**Issue by ChunlingHu** [IntelLabs/ParallelAccelerator.jl#30]
Test source code:

``` .julia
importall ParallelAccelerator

function opt_At_mul_B!(U, X, W)
	 #At_mul_B!(U, X, W)  # u <- w'x
	 U = X' * W
end

function main(m::Int, k::Int, n::Int)
    U  = Array(Float64, n, k)
    W  = Array(Float64, m, k)   
    X = Array(Float64, m, n)
    fill!(W, 3)
    fill!(X, 5)
    opt_At_mul_B!(U, X, W)
    println("done")

end
main(100, 100, 200)
```

This test fails in CGen with error:

```
ERROR: LoadError: BoundsError: attempt to access 7-element Array{Any,1}:
  :(:jl_new_array)
  :((top(apply_type))(Base.Array,Float64,2)::Type{Array{Float64,2}})
  :((top(svec))(Base.Any,Base.Any)::SimpleVector)
  Array{Float64,2}
 0
  GenSym(0)
 0
  at index [8]
```

**Comment by ninegua** [comment]
You should put @acc around `opt_At_mul_B!`. CGen doesn't handle matrix multiplication (`*`) if it is inlined by Julia. 

Then, the next issue is that neither CGen or DomainIR handles transpose. But this can be a quick fix.

**Comment by ninegua** [comment]
Fixed.

**Comment by lkuper** [comment]
@ninegua, can you check in @ChunlingHu's example (with `@acc` added) into the test suite as a regression test for this issue?

**Comment by ChunlingHu** [comment]
I got another error using the last ParallelAccelerator:

/tmp/tmpJcw0z8/cgen_output0.cpp(53): error: identifier "transposebaselength" is undefined
      if (!(((m) * (n)) <= (transposebaselength))) goto label8;
                            ^

/tmp/tmpJcw0z8/cgen_output0.cpp(159): error: identifier "transposebaselength" is undefined
      if (!(((m) * (n)) <= ((4) * (transposebaselength)))) goto label12;
                                   ^

compilation aborted for /tmp/tmpJcw0z8/cgen_output0.cpp (code 2)
ERROR: LoadError: failed process: Process(`icpc -O3 -qopenmp -std=c++11 -g '' -fpic -c -o /tmp/tmpJcw0z8/cgen_output0.o /tmp/tmpJcw0z8/cgen_output0.cpp`, ProcessExited(2)) [2]

**Comment by ninegua** [comment]
The function is now part of our test cases in `test/misc.jl`. Everything works according to travis. Please check your local installation. @ChunlingHu
