### ISSUE TITLE
CompilerTools fails for test

### ISSUE THREAD

**Issue by ChunlingHu** [IntelLabs/ParallelAccelerator.jl#35]
Test source code:
```.julia
importall ParallelAccelerator

@acc function normalizeW(W::DenseMatrix{Float64}, k::Int)
    s = [sqrt(sumabs2(W[:,j])) for j in 1:k]
    scale!(W,s)
end

function main(m::Int, k::Int, n::Int)
    W  = Array(Float64, m, k)   
    fill!(W, 3)
    normalizeW(W, k)
    println("done")

end

main(100, 100, 200)
```
Error:
```
ERROR: LoadError: "from_expr: unknown ast :CompilerTools.LivenessAnalysis.AccessSummary"
```

**Comment by DrTodd13** [comment]
Looks like sumabs2 becomes a mapreduce and then cgen tries to translate that and eventually runs into something it doesn't support.  I think Paul should look into subabs2 getting transformed to domain IR operations.

**Comment by ninegua** [comment]
`sumabs2` is not a function we support in ParallelAccelerator. Please rewrite it as `sumabs2(a) = sum([x * x for x in a])`.

**Comment by ninegua** [comment]
We don't support `scale!` either. Please rewrite it as `scale!(a,b) = a = a .* b`

**Comment by ninegua** [comment]
Ok, we don't support `a .* b` where `a` and `b` are of different dimensions, but Julia supports it, and it behaves differently than `scale!(a,b)` when `a` is 2D and `b` is 1D. This is something we need to fix.

**Comment by ninegua** [comment]
To implement the exact Julia semantics for `.*` and the likes will likely incur some overhead that we don't want. Here is what I suggest how we handle expressions like `C = A .* B`:

1. the result dimension `ndims(C) = max(ndims(A), ndims(B))`.
2. for each dimension `i` in the result, its length is `max(size(A,i),size(B,i))`, AND
3. either `size(A, i) == 1` or `size(B, i) == 1`, or `size(A,i)==size(B,i)`

Without condition 3, we will have to perform `wraparound` reads, i.e., every index calculation needs a `mod` operation. An alternative is to do a runtime check and choose between a straight version and a `mod`ded version, which might be hard to implement with the presence of fusion and so on.

I suggest we impose condition 3 at runtime to avoid all `mod`s, and document this difference. Any thoughts? @DrTodd13 @lkuper @ChunlingHu @ehsantn

**Comment by ninegua** [comment]
It seems that supporting condition 3 (the result size of each dimension is a max of two inputs) would still break all sensible size equivalence inference that is a major enabler for loop fusion. So I'm inclined to stick with our current implementation, i.e., requiring dimension and size to exactly match for map operators such as `.*`.

One has to make explicit call to `reshape` or `broadcast` to perform dimension/size coalescing. We now already supports `reshape`, and additional support for `broadcast` is needed.

**Comment by ninegua** [comment]
Going back to the original program. The following works out (with range-fusion branch):

``` julia
@acc function normalizeW(W::DenseMatrix{Float64})
    (m, k) = size(W)
    s = [sqrt(sum(W[:,j] .* W[:,j])) for j in 1:k]
    W[:,:] = W .* [s[j] for i = 1:m, j=1:k]
    return W
end
```

The output code is 2 loops, which is optimal too. The quirks about `@inline` (as discussed in #41) prevents me from writing `scale!` as its own function using comprehension.

For functions such as `sumabs2, scale!, repmat` or even matrix multiply, the most straightforward way to optimize them is to define them in terms of operators that are already supported by ParallelAccelerator, and use `@inline` so that they can fuse into the callsite. But the trouble with `@inline` is that it doesn't always force inlining.

**Comment by ninegua** [comment]
With the new support of reduction along a specific dimension, the above program can be rewritten as:

~~~
 @acc function normalizeW(W::DenseMatrix{Float64})
    (m, k) = size(W)
    s = sqrt(sum(W .* W, 1))
    W[:,:] = W .* [s[1, j] for i = 1:m, j=1:k]
    return W
end
~~~

**Comment by ninegua** [comment]
I'm closing this unless there is a demand (and a solution) to support the exact semantics of `scale!`, or `broadcast!`.
