### ISSUE TITLE
Fix QuoteNode-related error against nightly Julia

### ISSUE THREAD

**Issue by lkuper** [IntelLabs/ParallelAccelerator.jl#37]
According to Travis, we're really close to being able to build all our examples on _nightly_ Julia.  The only failure looks like it's something to do with `QuoteNode`: https://travis-ci.org/IntelLabs/ParallelAccelerator.jl/jobs/97038224#L438

It'd be nice to get this fixed, because if we can run all our stuff against nightly Julia, then that clears the way to benchmarking against code that uses `@threads`.

**Comment by ninegua** [comment]
This either has already been fixed, or is no longer relevant. Future discussion about running against nightly (or 0.5) can continue in #53.
