### ISSUE TITLE
Crashing bug, related to range fusion?

### ISSUE THREAD

**Issue by lkuper** [IntelLabs/ParallelAccelerator.jl#38]
This makes Julia crash and dump core:

``` .julia
using ParallelAccelerator

@acc function f()
    W  = zeros(5, 5)
    s = sum(W[:,3])
end

f()
```

**Comment by DrTodd13** [comment]
Fixed in range-fusion branch.  Will soon be merged into master.

**Comment by ninegua** [comment]
If I change to `sum(W[3,:]` the generated C code looks wrong in the iteration space. There is no mention of literal `3` anywhere.
