### ISSUE TITLE
Calculate Pi example

### ISSUE THREAD

**Issue by ehsantn** [IntelLabs/ParallelAccelerator.jl#43]
The simple program below for calculating Pi fails. CGen chokes on allocations for some reason. 

More importantly, the AST coming from ParallelIR is not optimized properly. It has array allocations but no array should be allocated here. Also, the loops are not fused.

```julia
using ParallelAccelerator

@acc function calcPi(n::Int64)
    x = rand(n) .* 2 .- 1
    y = rand(n) .* 2 .- 1
    return 4.0*sum(x.*x .+ y.*y .< 1)/n
end

calcPi(1000)
```

**Comment by ehsantn** [comment]
A lot of the issues for this example seem to be related to #44. After making the constants explicit float values, it works. 

However, the extra allocations are still there.

**Comment by ninegua** [comment]
The allocations come with `rand(n)`. The allocated array is an input to inplace mmap, and is no longer needed after fusion. @DrTodd13 do you think it is possible to get rid of this allocation?

**Comment by ehsantn** [comment]
I think we could add a pass of removing allocations after fusion and allocation hoisting is done in `top_level_from_exprs()`. Any thoughts?

**Comment by ehsantn** [comment]
Removing allocations is implemented now.
