### ISSUE TITLE
Binary operators with one constant

### ISSUE THREAD

**Issue by ehsantn** [IntelLabs/ParallelAccelerator.jl#44]
Binary operators like .* are not translated to `mmap` when one input is a constant. DomainIR used to promote the constants but the new macro pass doesn't do it.

```julia
@acc function example(x::Array{Float64,1})
    return x.*2
end
```

**Comment by ninegua** [comment]
I thought I fixed this a week ago? Let me double check which branch I pushed to. But the reason the above didn't work for you was that it required `x.*2.0` to work, i.e. the type must match. I made a patch that relaxed this requirement. So the above should work after this patch.

**Comment by ninegua** [comment]
The patch 2857ef335c5da7b15d6a126fe81616bb5b839ff3 is in range-fusion branch. Believe we are very close to merging range-fusion into master.

**Comment by ehsantn** [comment]
Thanks, Paul. Sounds good.

**Comment by ninegua** [comment]
I cherry picked the commits from range-fusion branch, and this is now working.
