### ISSUE TITLE
Liveness Analysis issue

### ISSUE THREAD

**Issue by ehsantn** [IntelLabs/ParallelAccelerator.jl#45]
I’m using liveness analysis after ParallelIR translation (before flattening) to remove extra allocations. A simple callback is used to ignore allocations in liveness analysis (calls pir_live_cb for others). If an array is allocated but is not in defs of any block (just uses) then it can be removed.

The liveness results don’t seem to be valid for some cases like our abs() test and blackscholes. The allocated array is in LiveIn instead of defs. Looking at liveness logs, the array is in defs in the process but at some point the liveness data is overwritten. Any idea what could be wrong?

**Comment by DrTodd13** [comment]
Can you provide more detailed steps to reproduce?  I've looked at abs a bit and can't see where there is an array that is allocated that shouldn't be in defs.  Similarly for blackscholes, what in that application is allocated and not otherwise used?

**Comment by ehsantn** [comment]
I don't see how the changes could help but it seems to be working after the merge of range-fusion branch. I'll enable the remove extra allocation optimization to see if any issue comes up later.
