### ISSUE TITLE
Mac OS build failure

### ISSUE THREAD

**Issue by ehsantn** [IntelLabs/ParallelAccelerator.jl#47]
Mac build is broken. I think it is because `from_parforstart_serial` is not updated with the recent changes for reductions. @ninegua 

Why is Mac build in the Travis allowed failure list? A lot of Julia users have Macs.

**Comment by ehsantn** [comment]
The issue is fixed now with 6011c2ff13e892894401da344e0a44f6cbff33c3.

**Comment by lkuper** [comment]
+1 for not having Mac builds on the allowed failure list anymore.  The CompilerTools Travis build has had Mac builds as a first-class citizen for some time.  It's probably about time we held ParallelAccelerator to the same standard.
