### ISSUE TITLE
Character handling at Julia/C++ interface seems to be broken

### ISSUE THREAD

**Issue by lkuper** [IntelLabs/ParallelAccelerator.jl#48]
While working on strings, we discovered the following bug when returning a character literal from an `@acc`-annotated function:

``` .julia
using ParallelAccelerator

@acc function f()
    return 'a'
end

println(f())
```

prints `�` instead of the expected `a`.

The generated function is just:

```
void ppfp7005(char * __restrict ret0)
{
*ret0 = 'a';
return;

}
```

and nothing else in the generated code looks suspicious.  So it seems the problem isn't in the generated code, but rather at the Julia/C++ boundary.

**Comment by lkuper** [comment]
Possibly the same bug: running the following code through CGen produces a warning from ICC ("warning #1899: multicharacter character literal (potential portability problem)" and an error from GCC ("character too large for enclosing character literal type"):

``` .julia
@acc function f1()
    x = "hello"
    return UInt8(x[3])
end
```

**Comment by ehsantn** [comment]
I fixed the first example in ad5351f7dc12f9e077e3319ac36a6a64941dd304. Characters coming from C should have Cchar type in Julia, and then converted to Char type.

Char is UTF-8 which can be multibyte while Cchar is ASCII which is always single byte. This is why you were seeing a weird character.

Strings need a lot more work to be handled properly. This work needs a good application to drive it.

http://docs.julialang.org/en/release-0.4/manual/calling-c-and-fortran-code/

**Comment by lkuper** [comment]
@ehsantn Thanks for taking a look at this!  I agree about applications.  I think @rajbarik might have some ideas about applications that require string support.

**Comment by ninegua** [comment]
Believe we can ignore the multichar warning for now. String tests are added in 6189d00300d9b5233b551760a2382113de3cc6a5. I'm closing this ticket for now.
