### ISSUE TITLE
Request: caching of function compilation

### ISSUE THREAD

**Issue by rened** [IntelLabs/ParallelAccelerator.jl#5]
Really fantastic package!

I am sure you have thought of this: to be useful in practice it would be important to be able to cache the compiled functions. Are there any plans for this?

**Comment by lkuper** [comment]
Hi @rened,

ParallelAccelerator keeps a dictionary of functions it has optimized and avoids recompiling them if it's already compiled a version with the type signature it needs.  In fact, you can probably observe this happening if within one Julia session you include the same example a few times:

```
julia> include("black-scholes/black-scholes.jl")
iterations = 10000000
SELFPRIMED 44.709564979
checksum: 2.0954821257116845e8
rate = 4.395317278023734e6 opts/sec
SELFTIMED 2.275148611

julia> include("black-scholes/black-scholes.jl")
iterations = 10000000
SELFPRIMED 1.891581702
checksum: 2.0954821257116845e8
rate = 4.640280570889616e6 opts/sec
SELFTIMED 2.155042103

julia> include("black-scholes/black-scholes.jl")
iterations = 10000000
SELFPRIMED 2.048499532
checksum: 2.0954821257116845e8
rate = 4.724652289250207e6 opts/sec
SELFTIMED 2.116557873
```

The 44.7 seconds reported for the first `SELFPRIMED` is mostly compilation time, and you can see most of that time going away on subsequent calls.  Is that what you mean by caching of function compilation or did you have something else in mind?

**Comment by rened** [comment]
Thanks for the quick respoinse @lkuper! Yes, I have seen the `gOptFrameworkDict` in `makeWrapperFunc` doing this. I was wondering whether this could also be stored on disk, in something like `generated/$(hash(functionsAST)).bin` and reloaded if already present?

My use case would mean having a lot (20+) of functions compiled by `ParallelAccelerator`, and the compile time penalty would easily reach 10min per start.

**Comment by lkuper** [comment]
Ah, I see.  We don't yet support persistence between different invocations of Julia, but that's an interesting idea.  We're also hoping to improve the compile time, though!

**Comment by rened** [comment]
I saw that he actual compilation on the C side is very fast, so it is about caching the analysis on the Julia side.

I believe there are two steps on the Julia side, AST analysis and compilation. Caching I think is only feasible in between the two, once the analyzed and typed AST is available? If you could point me in the right direction I could play with that, trying to persistently cache the compilation phase.

**Comment by KristofferC** [comment]
Maybe you could try https://github.com/timholy/SnoopCompile.jl precompile the most common and time consuming methods.

**Comment by rened** [comment]
Thanks for the pointer @KristofferC, I'll check that out.

**Comment by KristofferC** [comment]
I tried it and it helped a bit. From ~22 second for first call -> 13 seconds.

**Comment by rened** [comment]
Nice!

Ok, so it would still be good to cache `ParallelAccelerator`'s compile phase (not the actual Julia code compilation, which SnoopCompile takes care of).

**Comment by KristofferC** [comment]
FYI it is only the first compilation that takes 13 seconds. The ones after the first takes ~0.5 seconds.

So even with precompiling the functions that run when I included the file there is still a significant one time cost at the first `@acc` compilation. Looking at the profiler it is a lot of type inference going on.

Maybe @timholy can explain why there is a one time cost on the first call even when running with full SnoopCompile.

**Comment by timholy** [comment]
julia's precompilation does not cache methods that have arguments that straddle modules, e.g.,
```jl
push!(::Vector{RGB{UFixed8}}}, ::RGB{UFixed8})`
```
involves `Base` (for `push!`), `FixedPointNumbers` (for `UFixed8`), and `ColorTypes` (for RGB). So this method will not be cached even if you ask that it be precompiled. This is a julia limitation, not a SnoopCompile limitation. (Such methods end up in the `discards` output of SnoopCompile's `parcel`, because it would waste time if you went ahead and precompiled them anyway.) The only existing workaround I know of is the `userimg.jl` mechanism. See the SnoopCompile docs for more detail.

@rened, if you want to cache the results of type inference, you could presumably store all that in a JLD file (though loading that file might not be faster, you would have to experiment).

**Comment by DrTodd13** [comment]
The time consuming part is Julia compiling the ParallelAccelerator code, not ParallelAccelerator optimizing functions through @acc.  Please see the README about the use of the embed() function.  This is the scenario it was designed for.  We saw initial compile times drop from 20s on one program down to 2.5s.  Yes, you still have to incur this every time.  If that doesn't dramatically help let us know.

**Comment by DrTodd13** [comment]
One other comment, you mentioned 20 functions needing to be optimized.  Normally, we would imagine that there is some driver function that calls those 20 and you just do @acc on that driver function.  Called functions are then automatically recursively optimized.  Is there something in the driver we don't support that stops this approach or is it really 20 totally separate functions you need to optimize?

**Comment by rened** [comment]
@DrTodd13 thanks for the hints, I will try this out! Putting those functions into a wrapper function should work.

**Comment by ehsantn** [comment]
Most of the compilation time is spent in type inference of `ParallelAccelerator` itself. After that, everything seems to be fast. `SnoopCompile` doesn't measure type inference time so it's not very useful here. The best solution is using `userimg.jl` according to README instructions as @DrTodd13 mentioned.

**Comment by KristofferC** [comment]
Yes, after using the `userimg.jl` method the first call is at 4 seconds which is perfectly fine for me.

I should RTFM more carefully, my apologies.

**Comment by rened** [comment]
Thanks everyone for their input!

**Comment by DrTodd13** [comment]
One issue here we need to address is that with the code embedded in the Julia exe, that Pkg.update() of ParallelAccelerator might appear to not have any effect because it would update the package but not the code embedded in the exe (which has priority).  It might be necessary to build Julia again after an update of ParallelAccelerator.  This is the downside of embedding and we need to work on a way of notifying or automating this process so that we don't forget it needs to be done.

**Comment by tkelman** [comment]
I fully expect userimg to go away in the future as it's a bit of a hack and not easily usable in a binary install of Julia. The main thing that userimg gives you but `__precompile__` doesn't yet is linking a shared library from the cached compilation result. That requires a toolchain and linker to be present, but it's likely that we'll be able to either bundle LLD or set up a package that manages installing LLD from binaries.
