### ISSUE TITLE
Fusion is broken

### ISSUE THREAD

**Issue by ninegua** [IntelLabs/ParallelAccelerator.jl#57]
@ehsantn Looks like your set of commits on Feb 15 broke fusion. The following program no longer gives any fused loop with ParallelAccelerator b9e4715f39a2723cf2df597f46212e80eca7e15f (Feb 15) and CompilerTools [9cafa88](https://github.com/IntelLabs/CompilerTools.jl/commit/9cafa884fae8f2799ae839f0c98482289c6b0be5) (Feb 15):

```
using ParallelAccelerator
@acc function f(A, B)
  M = length(A)
  C = zeros(Float64, M)
  D = zeros(Float64, M)
  E = zeros(Float64, M)
  sum(A.+C)+sum(B.+D)+sum(E)
end
print(f([1,2,3], [1,2,3]))
```

But it fused into two loops with ParallelAccelerator 4383a7985d90464fd4b30c9cd96047ed10cec1a6 (Feb 11), and CompilerTools [9cafa88](https://github.com/IntelLabs/CompilerTools.jl/commit/9cafa884fae8f2799ae839f0c98482289c6b0be5) (Feb 15). Ideally it should fuse into one loop. But that is probably a different issue.

**Comment by ehsantn** [comment]
I haven't changed anything in fusion codes but the AST before fusion might have changed. I'll take a look.

**Comment by ninegua** [comment]
Could be related to changes in equivalence class.

**Comment by ehsantn** [comment]
The equivalence class pass output is identical for both commits.

**Comment by ehsantn** [comment]
The problem was that the `SymbolNode` arguments to `:alloc` are replaced with the `Symbols` in the first pass of equivalence class but the second pass was expecting `SymbolNodes`. This sort variable type expectation can cause other issues also I think.
