### ISSUE TITLE
UndefVarError: Helper not defined error

### ISSUE THREAD

**Issue by jiahao** [IntelLabs/ParallelAccelerator.jl#60]
I was unable to run the Black-Scholes example from the [ParallelAccelerator guest blog post](http://julialang.org/blog/2016/03/parallelaccelerator), even on the most recent master version of ParallelAccelerator.jl. 

I'm running the julia 0.4.3 release version on OS X 10.11.3, on an Intel i5 MacBook Pro (Retina, 13", late 2013), on a machine without Intel compilers or MKL installed.

```jl
julia> include("pa.jl")
ERROR: LoadError: LoadError: LoadError: UndefVarError: Helper not defined
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
while loading /Users/jiahao/.julia/v0.4/ParallelAccelerator/src/domain-ir.jl, in expression starting on line 37
while loading /Users/jiahao/.julia/v0.4/ParallelAccelerator/src/ParallelAccelerator.jl, in expression starting on line 235
while loading /Users/jiahao/sandbox/pa.jl, in expression starting on line 1
```

When building the package, the following output was produced:

```jl
INFO: Building ParallelAccelerator
ParallelAccelerator: build.jl begin.
ParallelAccelerator: Building j2c-array shared library
MKL not detected (optional)
OpenBlas not detected (optional)
Using g++ to build ParallelAccelerator array runtime.
ParallelAccelerator: build.jl done.
```

Ref: JuliaLang/julialang.github.com#353

**Comment by ehsantn** [comment]
Looks like you might not have the latest version of `CompilerTools` package. Could you update your packages and try again?

**Comment by lkuper** [comment]
@jiahao Did `Pkg.checkout("CompilerTools")` solve the problem?

@ehsantn Maybe we should put the instructions in http://parallelacceleratorjl.readthedocs.org/en/latest/install.html back in the README.

**Comment by ehsantn** [comment]
There is no need @lkuper. The problem was that CompilerTools was tagged after ParallelAccelerator was tagged but it is fixed.

**Comment by jiahao** [comment]
Works for me now after a `Pkg.update()`. Thanks!
