### ISSUE TITLE
LoadError

### ISSUE THREAD

**Issue by pevnak** [IntelLabs/ParallelAccelerator.jl#70]
Hello,
I have tried to use ParallelAccelerator with Julia 0.4.3 on CentOS release 6.6 (Final) with gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11).
When I type using ParallelAccelerator into freshly launched Julia gives me this error.
I do not know, what is wrong.

`
ERROR: LoadError: LoadError: UndefVarError: LambdaInfo not defined

 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
while loading /home/pevnak/.julia/v0.4/ParallelAccelerator/src/domain-ir.jl, in expression starting on line 193
while loading /home/pevnak/.julia/v0.4/ParallelAccelerator/src/ParallelAccelerator.jl, in expression starting on line 193`

**Comment by ninegua** [comment]
We have recently renamed `LambdaInfo` to `LambdaVarInfo` in CompilerTools.jl, and updated ParallelAccelerator.jl accordingly. So it looks like you have an old version of ParallelAccelerator. Please update both packages to the latest master branch and try again. We have more instructions on http://parallelacceleratorjl.readthedocs.org/en/latest/install.html

**Comment by lkuper** [comment]
@pevnak Did @ninegua's suggestion (to update the ParallelAccelerator and CompilerTools packages to the latest version) help?  If not, feel free to reopen this issue.

**Comment by pevnak** [comment]
Yes,
it has worked. 
Thank you very much.
Best wishes,
Tomas
