### ISSUE TITLE
Fusion issue

### ISSUE THREAD

**Issue by ehsantn** [IntelLabs/ParallelAccelerator.jl#87]
With the recent changes to `DomainLambda` and `mmapInline`, logistic regression no longer fuses properly. The data-parallel computation is now six loops instead of one.

**Comment by ninegua** [comment]
Looks like the removal of `mmapInline` exposes a bug in ParallelIR fusion at (the wrong order of) checking indices access pattern. It is fixed in 90f6064fbe1a349c1ab25acc924b552849258edf.

**Comment by ehsantn** [comment]
Thanks! I think one more loop of logistic regression is fused now than before with this fix.
