### ISSUE TITLE
Drop unnecessary packages from REQUIRE

### ISSUE THREAD

**Issue by blakejohnson** [IntelLabs/ParallelAccelerator.jl#99]
Several packages are listed in REQUIRE that are only used in the examples, and thus could be dropped. I didn't do an exhaustive search, but at minimum it looks like you could remove: Images, ImageMagick, and Winston.

**Comment by lkuper** [comment]
Yeah, we did this so that our examples would run right out of the box, for instance on Travis. But there are other ways to handle that.

**Comment by blakejohnson** [comment]
Well, if it is for testing, you can drop a REQUIRE file inside your test/ directory and get that for free.

**Comment by KristofferC** [comment]
https://github.com/IntelLabs/ParallelAccelerator.jl/issues/10#issuecomment-152515072

:)

**Comment by ehsantn** [comment]
Let's drop the dependencies. They are constant source of trouble, especially because they need binary libraries.

**Comment by lkuper** [comment]
Yeah, I now disagree with my past self in [this comment](https://github.com/IntelLabs/ParallelAccelerator.jl/issues/10#issuecomment-153201576).  The developers should have the `test/REQUIRE` packages installed already, and on Travis everything has to get installed every time anyway.  I'll just put the dependencies in `test/REQUIRE`.
